on: [ push, pull_request ]
name: Publish new release
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ macos-10.15, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test ./...
